/**
 * @fileoverview React wrappers for Material Web select components
 *
 * This file was auto-generated on 2025-09-02T08:37:42.149Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdFilledSelect as _MdFilledSelect } from '@material/web/select/filled-select.js'
import { MdOutlinedSelect as _MdOutlinedSelect } from '@material/web/select/outlined-select.js'
import { MdSelectOption as _MdSelectOption } from '@material/web/select/select-option.js'

/**
 * Props for the `MdFilledSelect` component.
 * This interface is used to provide the props for the `MdFilledSelect` component.
 *
 */
export type MdFilledSelectProps = ComponentProps<typeof MdFilledSelect>

/**
 * Props for the `MdOutlinedSelect` component.
 * This interface is used to provide the props for the `MdOutlinedSelect` component.
 *
 */
export type MdOutlinedSelectProps = ComponentProps<typeof MdOutlinedSelect>

/**
 * Props for the `MdSelectOption` component.
 * This interface is used to provide the props for the `MdSelectOption` component.
 *
 */
export type MdSelectOptionProps = ComponentProps<typeof MdSelectOption>

export interface MdFilledSelectElement extends _MdFilledSelect {}

export interface MdOutlinedSelectElement extends _MdOutlinedSelect {}

export interface MdSelectOptionElement extends _MdSelectOption {}

/**
 * Material Design Filled Select component.
 * This component is a React wrapper around the `md-filled-select` custom element.
 *
 * @component

 */
export const MdFilledSelect = createComponent({
  react: React,
  tagName: 'md-filled-select',
  elementClass: _MdFilledSelect,
  events: {},
})

/**
 * Material Design Outlined Select component.
 * This component is a React wrapper around the `md-outlined-select` custom element.
 *
 * @component

 */
export const MdOutlinedSelect = createComponent({
  react: React,
  tagName: 'md-outlined-select',
  elementClass: _MdOutlinedSelect,
  events: {},
})

/**
 * Material Design Select Option component.
 * This component is a React wrapper around the `md-select-option` custom element.
 *
 * @component

 */
export const MdSelectOption = createComponent({
  react: React,
  tagName: 'md-select-option',
  elementClass: _MdSelectOption,
  events: {},
})
