/**
 * @fileoverview React wrappers for Material Web ripple components
 * 
 * This file was auto-generated on 2025-09-02T08:29:48.044Z
 * 
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 * 
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { ComponentProps } from 'react'
import { MdRipple as _MdRipple } from '@material/web/ripple/ripple.js'

/**
 * Props for the `MdRipple` component.
 * This interface is used to provide the props for the `MdRipple` component.
 *
 */
export type MdRippleProps = ComponentProps<typeof MdRipple>

export interface MdRippleElement extends _MdRipple {}

/**
 * Material Design Ripple component.
 * This component is a React wrapper around the `md-ripple` custom element.
 *
 * @component

 */
export const MdRipple = createComponent({
    react: React,
    tagName: 'md-ripple',
    elementClass: _MdRipple,
    events: {},
})
