/**
 * @fileoverview React wrappers for Material Web switch components
 * 
 * This file was auto-generated on 2025-09-02T08:29:48.046Z
 * 
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 * 
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { ComponentProps } from 'react'
import { MdSwitch as _MdSwitch } from '@material/web/switch/switch.js'

/**
 * Props for the `MdSwitch` component.
 * This interface is used to provide the props for the `MdSwitch` component.
 *
 */
export type MdSwitchProps = ComponentProps<typeof MdSwitch>

export interface MdSwitchElement extends _MdSwitch {}

/**
 * Material Design Switch component.
 * This component is a React wrapper around the `md-switch` custom element.
 *
 * @component

 */
export const MdSwitch = createComponent({
    react: React,
    tagName: 'md-switch',
    elementClass: _MdSwitch,
    events: {
        onInput: 'input',
        onChange: 'change',
    },
})
