/**
 * @fileoverview React wrappers for Material Web slider components
 *
 * This file was auto-generated on 2025-10-11T02:53:07.895Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdSlider as _MdSlider } from '@material/web/slider/slider.js'

/**
 * Props for the `MdSlider` component.
 * This interface is used to provide the props for the `MdSlider` component.
 *
 */
export type MdSliderProps = ComponentProps<typeof MdSlider>

export interface MdSliderElement extends _MdSlider {}

/**
 * Material Design Slider component.
 * This component is a React wrapper around the `md-slider` custom element.
 *
 * @component

 */
export const MdSlider = createComponent({
  react: React,
  tagName: 'md-slider',
  elementClass: _MdSlider,
  events: {
    onChange: 'change',
    onInput: 'input',
  },
})
