/**
 * @fileoverview React wrappers for Material Web checkbox components
 * 
 * This file was auto-generated on 2025-09-02T08:29:48.036Z
 * 
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 * 
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { ComponentProps } from 'react'
import { MdCheckbox as _MdCheckbox } from '@material/web/checkbox/checkbox.js'

/**
 * Props for the `MdCheckbox` component.
 * This interface is used to provide the props for the `MdCheckbox` component.
 *
 */
export type MdCheckboxProps = ComponentProps<typeof MdCheckbox>

export interface MdCheckboxElement extends _MdCheckbox {}

/**
 * Material Design Checkbox component.
 * This component is a React wrapper around the `md-checkbox` custom element.
 *
 * @component

 */
export const MdCheckbox = createComponent({
    react: React,
    tagName: 'md-checkbox',
    elementClass: _MdCheckbox,
    events: {
        onChange: 'change',
        onInput: 'input',
    },
})
