/**
 * @fileoverview React wrappers for Material Web chips components
 *
 * This file was auto-generated on 2025-10-11T02:53:07.888Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdAssistChip as _MdAssistChip } from '@material/web/chips/assist-chip.js'
import { MdChipSet as _MdChipSet } from '@material/web/chips/chip-set.js'
import { MdFilterChip as _MdFilterChip } from '@material/web/chips/filter-chip.js'
import { MdInputChip as _MdInputChip } from '@material/web/chips/input-chip.js'
import { MdSuggestionChip as _MdSuggestionChip } from '@material/web/chips/suggestion-chip.js'

/**
 * Props for the `MdAssistChip` component.
 * This interface is used to provide the props for the `MdAssistChip` component.
 *
 */
export type MdAssistChipProps = ComponentProps<typeof MdAssistChip>

/**
 * Props for the `MdChipSet` component.
 * This interface is used to provide the props for the `MdChipSet` component.
 *
 */
export type MdChipSetProps = ComponentProps<typeof MdChipSet>

/**
 * Props for the `MdFilterChip` component.
 * This interface is used to provide the props for the `MdFilterChip` component.
 *
 */
export type MdFilterChipProps = ComponentProps<typeof MdFilterChip>

/**
 * Props for the `MdInputChip` component.
 * This interface is used to provide the props for the `MdInputChip` component.
 *
 */
export type MdInputChipProps = ComponentProps<typeof MdInputChip>

/**
 * Props for the `MdSuggestionChip` component.
 * This interface is used to provide the props for the `MdSuggestionChip` component.
 *
 */
export type MdSuggestionChipProps = ComponentProps<typeof MdSuggestionChip>

export interface MdAssistChipElement extends _MdAssistChip {}

export interface MdChipSetElement extends _MdChipSet {}

export interface MdFilterChipElement extends _MdFilterChip {}

export interface MdInputChipElement extends _MdInputChip {}

export interface MdSuggestionChipElement extends _MdSuggestionChip {}

/**
 * Material Design Assist Chip component.
 * This component is a React wrapper around the `md-assist-chip` custom element.
 *
 * @component

 */
export const MdAssistChip = createComponent({
  react: React,
  tagName: 'md-assist-chip',
  elementClass: _MdAssistChip,
  events: {},
})

/**
 * Material Design Chip Set component.
 * This component is a React wrapper around the `md-chip-set` custom element.
 *
 * @component

 */
export const MdChipSet = createComponent({
  react: React,
  tagName: 'md-chip-set',
  elementClass: _MdChipSet,
  events: {},
})

/**
 * Material Design Filter Chip component.
 * This component is a React wrapper around the `md-filter-chip` custom element.
 *
 * @component

 */
export const MdFilterChip = createComponent({
  react: React,
  tagName: 'md-filter-chip',
  elementClass: _MdFilterChip,
  events: {},
})

/**
 * Material Design Input Chip component.
 * This component is a React wrapper around the `md-input-chip` custom element.
 *
 * @component

 */
export const MdInputChip = createComponent({
  react: React,
  tagName: 'md-input-chip',
  elementClass: _MdInputChip,
  events: {},
})

/**
 * Material Design Suggestion Chip component.
 * This component is a React wrapper around the `md-suggestion-chip` custom element.
 *
 * @component

 */
export const MdSuggestionChip = createComponent({
  react: React,
  tagName: 'md-suggestion-chip',
  elementClass: _MdSuggestionChip,
  events: {},
})
