/**
 * @fileoverview React wrappers for Material Web dialog components
 *
 * This file was auto-generated on 2025-09-02T08:37:42.142Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdDialog as _MdDialog } from '@material/web/dialog/dialog.js'

/**
 * Props for the `MdDialog` component.
 * This interface is used to provide the props for the `MdDialog` component.
 *
 */
export type MdDialogProps = ComponentProps<typeof MdDialog>

export interface MdDialogElement extends _MdDialog {}

/**
 * Material Design Dialog component.
 * This component is a React wrapper around the `md-dialog` custom element.
 *
 * @component

 */
export const MdDialog = createComponent({
  react: React,
  tagName: 'md-dialog',
  elementClass: _MdDialog,
  events: {},
})
