/**
 * @fileoverview React wrappers for Material Web fab components
 *
 * This file was auto-generated on 2025-09-02T08:37:42.144Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdBrandedFab as _MdBrandedFab } from '@material/web/fab/branded-fab.js'
import { MdFab as _MdFab } from '@material/web/fab/fab.js'

/**
 * Props for the `MdBrandedFab` component.
 * This interface is used to provide the props for the `MdBrandedFab` component.
 *
 */
export type MdBrandedFabProps = ComponentProps<typeof MdBrandedFab>

/**
 * Props for the `MdFab` component.
 * This interface is used to provide the props for the `MdFab` component.
 *
 */
export type MdFabProps = ComponentProps<typeof MdFab>

export interface MdBrandedFabElement extends _MdBrandedFab {}

export interface MdFabElement extends _MdFab {}

/**
 * Material Design Branded Fab component.
 * This component is a React wrapper around the `md-branded-fab` custom element.
 *
 * @component

 */
export const MdBrandedFab = createComponent({
  react: React,
  tagName: 'md-branded-fab',
  elementClass: _MdBrandedFab,
  events: {},
})

/**
 * Material Design Fab component.
 * This component is a React wrapper around the `md-fab` custom element.
 *
 * @component

 */
export const MdFab = createComponent({
  react: React,
  tagName: 'md-fab',
  elementClass: _MdFab,
  events: {},
})
