/**
 * @fileoverview React wrappers for Material Web focus components
 * 
 * This file was auto-generated on 2025-09-02T08:29:48.040Z
 * 
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 * 
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { ComponentProps } from 'react'
import { MdFocusRing as _MdFocusRing } from '@material/web/focus/md-focus-ring.js'

/**
 * Props for the `MdFocusRing` component.
 * This interface is used to provide the props for the `MdFocusRing` component.
 *
 */
export type MdFocusRingProps = ComponentProps<typeof MdFocusRing>

export interface MdFocusRingElement extends _MdFocusRing {}

/**
 * Material Design Focus Ring component.
 * This component is a React wrapper around the `md-focus-ring` custom element.
 *
 * @component

 */
export const MdFocusRing = createComponent({
    react: React,
    tagName: 'md-focus-ring',
    elementClass: _MdFocusRing,
    events: {},
})
