/**
 * @fileoverview React wrappers for Material Web tabs components
 *
 * This file was auto-generated on 2025-10-11T02:53:07.896Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdPrimaryTab as _MdPrimaryTab } from '@material/web/tabs/primary-tab.js'
import { MdSecondaryTab as _MdSecondaryTab } from '@material/web/tabs/secondary-tab.js'
import { MdTabs as _MdTabs } from '@material/web/tabs/tabs.js'

/**
 * Props for the `MdPrimaryTab` component.
 * This interface is used to provide the props for the `MdPrimaryTab` component.
 *
 */
export type MdPrimaryTabProps = ComponentProps<typeof MdPrimaryTab>

/**
 * Props for the `MdSecondaryTab` component.
 * This interface is used to provide the props for the `MdSecondaryTab` component.
 *
 */
export type MdSecondaryTabProps = ComponentProps<typeof MdSecondaryTab>

/**
 * Props for the `MdTabs` component.
 * This interface is used to provide the props for the `MdTabs` component.
 *
 */
export type MdTabsProps = ComponentProps<typeof MdTabs>

export interface MdPrimaryTabElement extends _MdPrimaryTab {}

export interface MdSecondaryTabElement extends _MdSecondaryTab {}

export interface MdTabsElement extends _MdTabs {}

/**
 * Material Design Primary Tab component.
 * This component is a React wrapper around the `md-primary-tab` custom element.
 *
 * @component

 */
export const MdPrimaryTab = createComponent({
  react: React,
  tagName: 'md-primary-tab',
  elementClass: _MdPrimaryTab,
  events: {},
})

/**
 * Material Design Secondary Tab component.
 * This component is a React wrapper around the `md-secondary-tab` custom element.
 *
 * @component

 */
export const MdSecondaryTab = createComponent({
  react: React,
  tagName: 'md-secondary-tab',
  elementClass: _MdSecondaryTab,
  events: {},
})

/**
 * Material Design Tabs component.
 * This component is a React wrapper around the `md-tabs` custom element.
 *
 * @component

 */
export const MdTabs = createComponent({
  react: React,
  tagName: 'md-tabs',
  elementClass: _MdTabs,
  events: {},
})
