/**
 * @fileoverview React wrappers for Material Web progress components
 *
 * This file was auto-generated on 2025-09-02T08:37:42.148Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdCircularProgress as _MdCircularProgress } from '@material/web/progress/circular-progress.js'
import { MdLinearProgress as _MdLinearProgress } from '@material/web/progress/linear-progress.js'

/**
 * Props for the `MdCircularProgress` component.
 * This interface is used to provide the props for the `MdCircularProgress` component.
 *
 */
export type MdCircularProgressProps = ComponentProps<typeof MdCircularProgress>

/**
 * Props for the `MdLinearProgress` component.
 * This interface is used to provide the props for the `MdLinearProgress` component.
 *
 */
export type MdLinearProgressProps = ComponentProps<typeof MdLinearProgress>

export interface MdCircularProgressElement extends _MdCircularProgress {}

export interface MdLinearProgressElement extends _MdLinearProgress {}

/**
 * Material Design Circular Progress component.
 * This component is a React wrapper around the `md-circular-progress` custom element.
 *
 * @component

 */
export const MdCircularProgress = createComponent({
  react: React,
  tagName: 'md-circular-progress',
  elementClass: _MdCircularProgress,
  events: {},
})

/**
 * Material Design Linear Progress component.
 * This component is a React wrapper around the `md-linear-progress` custom element.
 *
 * @component

 */
export const MdLinearProgress = createComponent({
  react: React,
  tagName: 'md-linear-progress',
  elementClass: _MdLinearProgress,
  events: {},
})
