/**
 * @fileoverview React wrappers for Material Web menu components
 *
 * This file was auto-generated on 2025-09-02T08:37:42.147Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdMenuItem as _MdMenuItem } from '@material/web/menu/menu-item.js'
import { MdMenu as _MdMenu } from '@material/web/menu/menu.js'
import { MdSubMenu as _MdSubMenu } from '@material/web/menu/sub-menu.js'

/**
 * Props for the `MdMenuItem` component.
 * This interface is used to provide the props for the `MdMenuItem` component.
 *
 */
export type MdMenuItemProps = ComponentProps<typeof MdMenuItem>

/**
 * Props for the `MdMenu` component.
 * This interface is used to provide the props for the `MdMenu` component.
 *
 */
export type MdMenuProps = ComponentProps<typeof MdMenu>

/**
 * Props for the `MdSubMenu` component.
 * This interface is used to provide the props for the `MdSubMenu` component.
 *
 */
export type MdSubMenuProps = ComponentProps<typeof MdSubMenu>

export interface MdMenuItemElement extends _MdMenuItem {}

export interface MdMenuElement extends _MdMenu {}

export interface MdSubMenuElement extends _MdSubMenu {}

/**
 * Material Design Menu Item component.
 * This component is a React wrapper around the `md-menu-item` custom element.
 *
 * @component

 */
export const MdMenuItem = createComponent({
  react: React,
  tagName: 'md-menu-item',
  elementClass: _MdMenuItem,
  events: {
    onOpening: 'opening',
    onOpened: 'opened',
    onClosing: 'closing',
    onClosed: 'closed',
  },
})

/**
 * Material Design Menu component.
 * This component is a React wrapper around the `md-menu` custom element.
 *
 * @component

 */
export const MdMenu = createComponent({
  react: React,
  tagName: 'md-menu',
  elementClass: _MdMenu,
  events: {
    onOpening: 'opening',
    onOpened: 'opened',
    onClosing: 'closing',
    onClosed: 'closed',
  },
})

/**
 * Material Design Sub Menu component.
 * This component is a React wrapper around the `md-sub-menu` custom element.
 *
 * @component

 */
export const MdSubMenu = createComponent({
  react: React,
  tagName: 'md-sub-menu',
  elementClass: _MdSubMenu,
  events: {
    onOpening: 'opening',
    onOpened: 'opened',
    onClosing: 'closing',
    onClosed: 'closed',
  },
})
