/**
 * @fileoverview React wrappers for Material Web icon components
 *
 * This file was auto-generated on 2026-09-12T06:54:32.616Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdIcon as _MdIcon } from '@material/web/icon/icon.js'

/**
 * Props for the `MdIcon` component.
 * This interface is used to provide the props for the `MdIcon` component.
 *
 */
export type MdIconProps = ComponentProps<typeof MdIcon>

export interface MdIconElement extends _MdIcon {}

/**
 * Material Design Icon component.
 * This component is a React wrapper around the `md-icon` custom element.
 *
 * @component

 */
export const MdIcon = createComponent({
  react: React,
  tagName: 'md-icon',
  elementClass: _MdIcon,
  events: {},
})
