/**
 * @fileoverview React wrappers for Material Web radio components
 * 
 * This file was auto-generated on 2025-09-02T08:29:48.043Z
 * 
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 * 
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { ComponentProps } from 'react'
import { MdRadio as _MdRadio } from '@material/web/radio/radio.js'

/**
 * Props for the `MdRadio` component.
 * This interface is used to provide the props for the `MdRadio` component.
 *
 */
export type MdRadioProps = ComponentProps<typeof MdRadio>

export interface MdRadioElement extends _MdRadio {}

/**
 * Material Design Radio component.
 * This component is a React wrapper around the `md-radio` custom element.
 *
 * @component

 */
export const MdRadio = createComponent({
    react: React,
    tagName: 'md-radio',
    elementClass: _MdRadio,
    events: {
        onInput: 'input',
        onChange: 'change',
    },
})
