/**
 * @fileoverview React wrappers for Material Web iconbutton components
 *
 * This file was auto-generated on 2025-10-11T02:53:07.892Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdFilledIconButton as _MdFilledIconButton } from '@material/web/iconbutton/filled-icon-button.js'
import { MdFilledTonalIconButton as _MdFilledTonalIconButton } from '@material/web/iconbutton/filled-tonal-icon-button.js'
import { MdIconButton as _MdIconButton } from '@material/web/iconbutton/icon-button.js'
import { MdOutlinedIconButton as _MdOutlinedIconButton } from '@material/web/iconbutton/outlined-icon-button.js'

/**
 * Props for the `MdFilledIconButton` component.
 * This interface is used to provide the props for the `MdFilledIconButton` component.
 *
 */
export type MdFilledIconButtonProps = ComponentProps<typeof MdFilledIconButton>

/**
 * Props for the `MdFilledTonalIconButton` component.
 * This interface is used to provide the props for the `MdFilledTonalIconButton` component.
 *
 */
export type MdFilledTonalIconButtonProps = ComponentProps<typeof MdFilledTonalIconButton>

/**
 * Props for the `MdIconButton` component.
 * This interface is used to provide the props for the `MdIconButton` component.
 *
 */
export type MdIconButtonProps = ComponentProps<typeof MdIconButton>

/**
 * Props for the `MdOutlinedIconButton` component.
 * This interface is used to provide the props for the `MdOutlinedIconButton` component.
 *
 */
export type MdOutlinedIconButtonProps = ComponentProps<typeof MdOutlinedIconButton>

export interface MdFilledIconButtonElement extends _MdFilledIconButton {}

export interface MdFilledTonalIconButtonElement extends _MdFilledTonalIconButton {}

export interface MdIconButtonElement extends _MdIconButton {}

export interface MdOutlinedIconButtonElement extends _MdOutlinedIconButton {}

/**
 * Material Design Filled Icon Button component.
 * This component is a React wrapper around the `md-filled-icon-button` custom element.
 *
 * @component

 */
export const MdFilledIconButton = createComponent({
  react: React,
  tagName: 'md-filled-icon-button',
  elementClass: _MdFilledIconButton,
  events: {
    onInput: 'input',
    onChange: 'change',
  },
})

/**
 * Material Design Filled Tonal Icon Button component.
 * This component is a React wrapper around the `md-filled-tonal-icon-button` custom element.
 *
 * @component

 */
export const MdFilledTonalIconButton = createComponent({
  react: React,
  tagName: 'md-filled-tonal-icon-button',
  elementClass: _MdFilledTonalIconButton,
  events: {
    onInput: 'input',
    onChange: 'change',
  },
})

/**
 * Material Design Icon Button component.
 * This component is a React wrapper around the `md-icon-button` custom element.
 *
 * @component

 */
export const MdIconButton = createComponent({
  react: React,
  tagName: 'md-icon-button',
  elementClass: _MdIconButton,
  events: {
    onInput: 'input',
    onChange: 'change',
  },
})

/**
 * Material Design Outlined Icon Button component.
 * This component is a React wrapper around the `md-outlined-icon-button` custom element.
 *
 * @component

 */
export const MdOutlinedIconButton = createComponent({
  react: React,
  tagName: 'md-outlined-icon-button',
  elementClass: _MdOutlinedIconButton,
  events: {
    onInput: 'input',
    onChange: 'change',
  },
})
