/**
 * @fileoverview React wrappers for Material Web field components
 *
 * This file was auto-generated on 2025-10-09T02:59:38.256Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdFilledField as _MdFilledField } from '@material/web/field/filled-field.js'
import { MdOutlinedField as _MdOutlinedField } from '@material/web/field/outlined-field.js'

/**
 * Props for the `MdFilledField` component.
 * This interface is used to provide the props for the `MdFilledField` component.
 *
 */
export type MdFilledFieldProps = ComponentProps<typeof MdFilledField>

/**
 * Props for the `MdOutlinedField` component.
 * This interface is used to provide the props for the `MdOutlinedField` component.
 *
 */
export type MdOutlinedFieldProps = ComponentProps<typeof MdOutlinedField>

export interface MdFilledFieldElement extends _MdFilledField {}

export interface MdOutlinedFieldElement extends _MdOutlinedField {}

/**
 * Material Design Filled Field component.
 * This component is a React wrapper around the `md-filled-field` custom element.
 *
 * @component

 */
export const MdFilledField = createComponent({
  react: React,
  tagName: 'md-filled-field',
  elementClass: _MdFilledField,
  events: {},
})

/**
 * Material Design Outlined Field component.
 * This component is a React wrapper around the `md-outlined-field` custom element.
 *
 * @component

 */
export const MdOutlinedField = createComponent({
  react: React,
  tagName: 'md-outlined-field',
  elementClass: _MdOutlinedField,
  events: {},
})
