/**
 * @fileoverview React wrappers for Material Web elevation components
 *
 * This file was auto-generated on 2025-09-02T08:37:42.143Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdElevation as _MdElevation } from '@material/web/elevation/elevation.js'

/**
 * Props for the `MdElevation` component.
 * This interface is used to provide the props for the `MdElevation` component.
 *
 */
export type MdElevationProps = ComponentProps<typeof MdElevation>

export interface MdElevationElement extends _MdElevation {}

/**
 * Material Design Elevation component.
 * This component is a React wrapper around the `md-elevation` custom element.
 *
 * @component

 */
export const MdElevation = createComponent({
  react: React,
  tagName: 'md-elevation',
  elementClass: _MdElevation,
  events: {},
})
