/**
 * @fileoverview React wrappers for Material Web divider components
 *
 * This file was auto-generated on 2025-09-02T08:37:42.143Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdDivider as _MdDivider } from '@material/web/divider/divider.js'

/**
 * Props for the `MdDivider` component.
 * This interface is used to provide the props for the `MdDivider` component.
 *
 */
export type MdDividerProps = ComponentProps<typeof MdDivider>

export interface MdDividerElement extends _MdDivider {}

/**
 * Material Design Divider component.
 * This component is a React wrapper around the `md-divider` custom element.
 *
 * @component

 */
export const MdDivider = createComponent({
  react: React,
  tagName: 'md-divider',
  elementClass: _MdDivider,
  events: {},
})
