/**
 * @fileoverview React wrappers for Material Web button components
 *
 * This file was auto-generated on 2025-10-11T02:53:07.886Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdElevatedButton as _MdElevatedButton } from '@material/web/button/elevated-button.js'
import { MdFilledButton as _MdFilledButton } from '@material/web/button/filled-button.js'
import { MdFilledTonalButton as _MdFilledTonalButton } from '@material/web/button/filled-tonal-button.js'
import { MdOutlinedButton as _MdOutlinedButton } from '@material/web/button/outlined-button.js'
import { MdTextButton as _MdTextButton } from '@material/web/button/text-button.js'

/**
 * Props for the `MdElevatedButton` component.
 * This interface is used to provide the props for the `MdElevatedButton` component.
 *
 */
export type MdElevatedButtonProps = ComponentProps<typeof MdElevatedButton>

/**
 * Props for the `MdFilledButton` component.
 * This interface is used to provide the props for the `MdFilledButton` component.
 *
 */
export type MdFilledButtonProps = ComponentProps<typeof MdFilledButton>

/**
 * Props for the `MdFilledTonalButton` component.
 * This interface is used to provide the props for the `MdFilledTonalButton` component.
 *
 */
export type MdFilledTonalButtonProps = ComponentProps<typeof MdFilledTonalButton>

/**
 * Props for the `MdOutlinedButton` component.
 * This interface is used to provide the props for the `MdOutlinedButton` component.
 *
 */
export type MdOutlinedButtonProps = ComponentProps<typeof MdOutlinedButton>

/**
 * Props for the `MdTextButton` component.
 * This interface is used to provide the props for the `MdTextButton` component.
 *
 */
export type MdTextButtonProps = ComponentProps<typeof MdTextButton>

export interface MdElevatedButtonElement extends _MdElevatedButton {}

export interface MdFilledButtonElement extends _MdFilledButton {}

export interface MdFilledTonalButtonElement extends _MdFilledTonalButton {}

export interface MdOutlinedButtonElement extends _MdOutlinedButton {}

export interface MdTextButtonElement extends _MdTextButton {}

/**
 * Material Design Elevated Button component.
 * This component is a React wrapper around the `md-elevated-button` custom element.
 *
 * @component

 */
export const MdElevatedButton = createComponent({
  react: React,
  tagName: 'md-elevated-button',
  elementClass: _MdElevatedButton,
  events: {},
})

/**
 * Material Design Filled Button component.
 * This component is a React wrapper around the `md-filled-button` custom element.
 *
 * @component

 */
export const MdFilledButton = createComponent({
  react: React,
  tagName: 'md-filled-button',
  elementClass: _MdFilledButton,
  events: {},
})

/**
 * Material Design Filled Tonal Button component.
 * This component is a React wrapper around the `md-filled-tonal-button` custom element.
 *
 * @component

 */
export const MdFilledTonalButton = createComponent({
  react: React,
  tagName: 'md-filled-tonal-button',
  elementClass: _MdFilledTonalButton,
  events: {},
})

/**
 * Material Design Outlined Button component.
 * This component is a React wrapper around the `md-outlined-button` custom element.
 *
 * @component

 */
export const MdOutlinedButton = createComponent({
  react: React,
  tagName: 'md-outlined-button',
  elementClass: _MdOutlinedButton,
  events: {},
})

/**
 * Material Design Text Button component.
 * This component is a React wrapper around the `md-text-button` custom element.
 *
 * @component

 */
export const MdTextButton = createComponent({
  react: React,
  tagName: 'md-text-button',
  elementClass: _MdTextButton,
  events: {},
})
