/**
 * @fileoverview React wrappers for Material Web textfield components
 *
 * This file was auto-generated on 2025-10-09T02:59:38.261Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdFilledTextField as _MdFilledTextField } from '@material/web/textfield/filled-text-field.js'
import { MdOutlinedTextField as _MdOutlinedTextField } from '@material/web/textfield/outlined-text-field.js'

/**
 * Props for the `MdFilledTextField` component.
 * This interface is used to provide the props for the `MdFilledTextField` component.
 *
 */
export type MdFilledTextFieldProps = ComponentProps<typeof MdFilledTextField>

/**
 * Props for the `MdOutlinedTextField` component.
 * This interface is used to provide the props for the `MdOutlinedTextField` component.
 *
 */
export type MdOutlinedTextFieldProps = ComponentProps<typeof MdOutlinedTextField>

export interface MdFilledTextFieldElement extends _MdFilledTextField {}

export interface MdOutlinedTextFieldElement extends _MdOutlinedTextField {}

/**
 * Material Design Filled Text Field component.
 * This component is a React wrapper around the `md-filled-text-field` custom element.
 *
 * @component

 */
export const MdFilledTextField = createComponent({
  react: React,
  tagName: 'md-filled-text-field',
  elementClass: _MdFilledTextField,
  events: {},
})

/**
 * Material Design Outlined Text Field component.
 * This component is a React wrapper around the `md-outlined-text-field` custom element.
 *
 * @component

 */
export const MdOutlinedTextField = createComponent({
  react: React,
  tagName: 'md-outlined-text-field',
  elementClass: _MdOutlinedTextField,
  events: {},
})
