/**
 * @fileoverview React wrappers for Material Web list components
 *
 * This file was auto-generated on 2025-10-11T02:53:07.893Z
 *
 * DO NOT EDIT MANUALLY - This file is generated by generate.js
 * To regenerate, run: npm run generate
 *
 * @generated
 */

'use client'

import { createComponent } from '@lit/react'
import React, { type ComponentProps } from 'react'
import { MdListItem as _MdListItem } from '@material/web/list/list-item.js'
import { MdList as _MdList } from '@material/web/list/list.js'

/**
 * Props for the `MdListItem` component.
 * This interface is used to provide the props for the `MdListItem` component.
 *
 */
export type MdListItemProps = ComponentProps<typeof MdListItem>

/**
 * Props for the `MdList` component.
 * This interface is used to provide the props for the `MdList` component.
 *
 */
export type MdListProps = ComponentProps<typeof MdList>

export interface MdListItemElement extends _MdListItem {}

export interface MdListElement extends _MdList {}

/**
 * Material Design List Item component.
 * This component is a React wrapper around the `md-list-item` custom element.
 *
 * @component

 */
export const MdListItem = createComponent({
  react: React,
  tagName: 'md-list-item',
  elementClass: _MdListItem,
  events: {},
})

/**
 * Material Design List component.
 * This component is a React wrapper around the `md-list` custom element.
 *
 * @component

 */
export const MdList = createComponent({
  react: React,
  tagName: 'md-list',
  elementClass: _MdList,
  events: {},
})
