name: Generate Wrappers Nightly

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-wrappers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate wrappers
      run: npm run generate

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain src/)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: regenerate wrappers"
        title: "chore: regenerate wrappers"
        body: |
          This PR was automatically created by the nightly wrapper generation workflow.

          The following changes were detected:
          - Updated wrapper files from generate.js

          Please review the changes and merge if they look correct.
        branch: update-wrappers
        delete-branch: true
        add-paths: |
          src/
